import basketballAssets from '@/assets/basketjoin/basketjoin'
import wanderVilniusAssets from '@/assets/wondervilnius/wandervilnius'
import sweetsecretsAssets from '@/assets/sweetsecrets/sweetsecrets'
import { StaticImageData } from 'next/image'

export type ImageType = {
  src: StaticImageData
  alt: string
}

export type WebsiteProjectType = {
  title: string
  slug: string
  link: string
  published: boolean
  logo: StaticImageData
  images: ImageType[]
  projectDescription: string
  myWorkDescription?: string
  stack?: string[]
  highlightKeywords?: string[]
}

export const projects: WebsiteProjectType[] = [
  {
    title: 'BasketJoin',
    slug: 'basketjoin',
    link: 'https://basket-join.vercel.app',
    published: true,
    logo: basketballAssets.logo,
    images: [
      { src: basketballAssets.basketball1, alt: 'BasketJoin Schedule Page' },
      { src: basketballAssets.basketball2, alt: 'BasketJoin Profile Page' },
      { src: basketballAssets.basketball3, alt: 'BasketJoin Admin League Creation' },
      { src: basketballAssets.basketball4, alt: 'BasketJoin Payments Dashboard' },
      { src: basketballAssets.basketball5, alt: 'BasketJoin League Details' },
      { src: basketballAssets.basketball6, alt: 'BasketJoin Admin Panel' },
      { src: basketballAssets.basketball7, alt: 'BasketJoin Game Roster' }
    ],
    projectDescription:
      'A basketball registration app built with Next.js and Tailwind CSS, featuring user authentication powered by Kinde. Users can create accounts and register for basketball games. The platform helps track whether enough players have signed up to play on Tuesday evenings or other selected days.',
    myWorkDescription: `I led the development of this basketball registration app, building a full-stack solution with Next.js and Tailwind CSS. The platform features authentication, allowing players to create accounts and register for games. I implemented a dynamic scheduling system that tracks player availability.
    Admin panel for managing games and players. Ability to add seasons and courts with complex schedules.`,
    stack: ['nextjs', 'tailwind', 'prisma', 'github actions', 'nextauth.js'],
    highlightKeywords: ['basketball registration app']
  },

  {
    title: 'Sweetsecrets',
    slug: 'sweetsecrets',
    link: 'https://sweetsecrets.app',
    published: true,
    logo: sweetsecretsAssets.logoMonochrome,
    images: [
      { src: sweetsecretsAssets.sweetsecrets1, alt: 'Sweetsecrets Landing Page' },
      { src: sweetsecretsAssets.sweetsecrets6, alt: 'Sweetsecrets Subscription Pricing' },
      { src: sweetsecretsAssets.sweetsecrets2, alt: 'Sweetsecrets Story Library' },
      // { src: sweetsecretsAssets.sweetsecrets3, alt: 'Sweetsecrets Story Reader' },
      { src: sweetsecretsAssets.sweetsecrets4, alt: 'Sweetsecrets Interactive Story Choices' },
      { src: sweetsecretsAssets.sweetsecrets5, alt: 'Sweetsecrets Profile and Story Settings' },
      { src: sweetsecretsAssets.sweetsecrets7, alt: 'Sweetsecrets Coin Store' }
    ],
    projectDescription:
      'Sweetsecrets is a personalized AI-generated romance story platform. Users complete a choice-dependent quiz funnel that shapes their story preferences — from character traits to plot direction — then receive custom romance stories generated by Claude AI, written in second-person present tense. The app features a coin-based economy where users purchase coins to unlock premium stories and exclusive content as in-app upsells, along with a social layer of likes and views on stories.',
    myWorkDescription:
      'Built the full product end-to-end — from choice-dependent onboarding funnels that branch based on user answers, to AI-powered story generation via Claude API, to a coin store with in-app purchases used for premium upsells. Implemented a likes and views system to drive engagement and surface popular stories. Integrated a CRM to manage user segments and lifecycle messaging. Set up a CI/CD pipeline using a Supabase–GitHub–Vercel chain for continuous deployments with database migrations handled automatically on each push.',
    stack: ['nextjs', 'tailwind', 'supabase', 'claude', 'vercel', 'github actions'],
    highlightKeywords: ['personalized AI-generated romance story', 'choice-dependent quiz funnel', 'coin-based economy']
  },
  {
    title: 'Fametonic',
    slug: 'fametonic',
    link: 'https://fametonic.com',
    published: false,
    logo: null as unknown as StaticImageData,
    images: [],
    projectDescription: '',
    myWorkDescription: 'Was responsible for backend development',
    stack: ['nestjs', 'typeorm', 'rabbitmq']
  },
  {
    title: 'WanderVilnius',
    slug: 'wandervilnius',
    link: 'https://www.wandervilnius.lt',
    published: false,
    logo: wanderVilniusAssets.logo,
    images: [],
    projectDescription:
      "WanderVilnius is your ultimate guide to exploring the heart of Lithuania's capital. Whether you're a first-time visitor or a local looking to rediscover hidden gems, our city tours offer a unique and immersive experience. Discover Vilnius' rich history, vibrant culture, and stunning architecture, from the medieval Old Town to modern-day landmarks. With expert guides and customizable itineraries, WanderVilnius makes it easy to explore the city's most iconic sites, charming neighborhoods, and local hotspots. Embark on a journey through time and beauty with WanderVilnius."
  }
]
